### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by efitzpatrick** [unitbvcv/image_processing_tool#15]
Hello! 
I am a student at Case Western Reserve University looking to build a similar tool for a lab project. I would like to use some snippets of code from your repository, but can't find a license. Please let me know if I would be able to use appropriate snippets of code provided correct attribution to your project. Also, really like your project! It was very well written/architectured. 
Thanks,
Ellie Fitzpatrick

**Comment by cosminpolifronie** [comment]
Hello Ellie,

We really didn't think this project would be found by somebody outside our university, but we're glad it happened 😄.

I've added a license to the project, GPLv3 that is. You're free to use this code anyway you want.

> Also, really like your project! It was very well written/architectured.
We're flattered, really. Thanks a lot! ❤️ 

Have fun with your project!
